---
- name: Add Dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - nut-server
  - nut-client

- name: Configure UPS Drivers
  copy: src=ups.conf dest=/etc/nut/ups.conf owner=root group=nut mode=0640
  notify:
  - nut

- name: Configure NUT
  copy: src=nut.conf dest=/etc/nut/nut.conf owner=root group=nut mode=0640
  notify:
  - nut

- name: Set nut network passwords
  template: src=upsd.users dest=/etc/nut/upsd.users owner=root group=nut mode=0640
  notify:
  - nut

- name: Create the nutmon user
  user: name=nutmon system=yes group=nut

- name: Configure UPSmon
  template: src=upsmon.conf dest=/etc/nut/upsmon.conf owner=root group=nut mode=0640
  notify:
  - nut

- name: Configure UPSD
  copy: src=upsd.conf dest=/etc/nut/upsd.conf owner=root group=nut mode=0644
  notify:
  - nut
