---
- hosts: print
  become: yes
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - core-daemons
    - core-programs
    - sshd
    - papercut
    - netlogon
    - upsmon
    - netdata
