---
- name: copy-icinga-files1
  copy: src=icingaweb2.sql dest=/tmp/icingaweb2.sql owner=root group=root mode=0600

- name: copy-icinga-files2
  template: src=icingaweb2-users.sql dest=/tmp/icingaweb2-users.sql owner=root group=root mode=0600

- name: set-up-icinga-database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.table }}"
    state: import
    target: "{{ item.sql }}"
  with_items:
    - { table: 'icinga', sql: '/usr/share/icinga2-ido-mysql/schema/mysql.sql' }
    - { table: 'icingaweb2', sql: '/tmp/icingaweb2.sql' }
    - { table: 'icingaweb2', sql: '/tmp/icingaweb2-users.sql'}

- name: delete-icinga-files
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - icingaweb2.sql
    - icingaweb2-users.sql

- name: icinga
  service: name=icinga2 state=restarted
