---
- name: Install InspIRCd
  xbps:
    pkg: inspircd
    state: present

- name: Configure firewall for InspIRCd
  copy:
    src: inspircd.rules
    dest: /etc/iptables.d/inspircd.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- include_vars: secret/inspircd_opers.yml

- name: Configure InspIRCd
  template:
    src: "{{ item }}"
    dest: /etc/inspircd/{{ item }}
    owner: root
    group: inspircd
    mode: 0640
  with_items:
    - inspircd.conf
    - links.conf
    - modules.conf
    - opers.conf
    - motd.txt
    - rules.txt
  notify:
    - inspircd

- name: Configure OpenSSL
  copy:
    src: dhparams.pem
    dest: /etc/inspircd/dhparams.pem
    owner: root
    group: root
    mode: 0644

- name: Copy SSL key and cert
  copy:
    src: secret/inspircd_{{ item }}
    dest: /etc/inspircd/{{ item }}
    owner: root
    group: inspircd
    mode: 0640
  with_items:
    - cert.pem
    - key.pem
  notify:
    - inspircd

- name: Enable inspircd runit service
  file:
    src: /etc/sv/inspircd
    dest: /var/service/inspircd
    state: link
