- name: networking
  shell: (ifdown --exclude=lo -a && ifup --exclude=lo -a)&
- name: iptables
  command: /etc/network/if-up.d/iptables
- name: ntp
  service: name=ntp state=restarted
- name: sshd
  service: name=ssh state=restarted
- name: nrpe-server
  service: name=nagios-nrpe-server state=restarted
