---
- name: Configure firewall
  copy: src=nslcd.rules dest=/etc/iptables.d/nslcd.rules owner=root group=root mode=0640
  notify:
  - iptables
- name: Install libpam-ldapd
  apt: name=libpam-ldapd state=present
- name: Stop nscd
  service: name=nscd state=stopped enabled=no
- name: Configure libpam-ldapd
  copy: src=nslcd.conf dest=/etc/nslcd.conf owner=root group=nslcd mode=0640
  notify:
  - nslcd
- name: Add ldap to nsswitch
  lineinfile: "dest=/etc/nsswitch.conf regexp='^{{ item }}:' insertafter=regex line='{{ item }}:         files ldap'"
  with_items:
  - passwd
  - group
  - shadow
