---
- name: Create a kiosk user
  user: name=kiosk groups=kiosk,video

- name: Install xinitrc
  copy: src=xinitrc dest=/home/kiosk/.xinitrc owner=kiosk group=kiosk mode=0750

- name: Install reboot cron
  copy: src=startup dest=/etc/cron.d/startup owner=root group=root mode=0750

- name: Ensure announcements path exists
  file: path=/opt/announcements state=directory owner=kiosk group=kiosk mode=0755
