---
- name: Add tftp-hpa Package
  apt: pkg={{ item }} state=present
  with_items:
  - tftp-hpa
  - tftpd-hpa

- name: Configure tftp-hpa
  copy: src=tftpd-hpa dest=/etc/default/ owner=root group=root mode=0644
  notify:
  - tftpd-hpa

- name: Install TFTP Rules
  copy: src=tftp.rules dest=/etc/iptables.d owner=root group=root mode=0640
  notify:
  - iptables

- name: Add conntrack_tftp module
  lineinfile: dest=/etc/modules line=ip_conntrack_tftp
  notify:
  - kmod

- name: Create Ubuntu TFTP Root
  file: path=/srv/tftp/ubuntu state=directory mode=0755 owner=root group=root

- name: Download the Ubuntu Installer
  get_url: url=http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/installer-amd64/current/images/netboot/netboot.tar.gz dest=/tmp/netboot.tar.gz

- name: Expand the Ubuntu Installer
  unarchive: src=/tmp/netboot.tar.gz dest=/srv/tftp/ubuntu/ copy=no creates=/srv/tftp/ubuntu/ubuntu-installer

- name: Install the CV Boot Menu Patch
  copy: src=ubuntu-bootmenu.cfg dest=/srv/tftp/ubuntu/ubuntu-installer/amd64/boot-screens/txt.cfg owner=root group=root mode=0664
