---
- name: Add audio packages
  apt: pkg={{ item }} state=present
  with_items:
  - alsa-base
  - alsa-utils
  - mplayer
  - mpd
  - mpc
  - ncmpcpp
  - tmux

- name: Configure MPD
  copy: src=mpd.conf dest=/etc/mpd.conf owner=mpd group=audio mode=0640

- name: Add cv to group audio
  user: name=cv groups=audio append=true
