---
- name: Configure firewall for ssh-box
  copy: src=ssh-box.rules dest=/etc/iptables.d/ssh-box.rules owner=root group=root mode=0640
  notify:
  - iptables
- name: Install ssh-box packages
  apt: pkg={{ item }} state=present
  with_items:
  - zsh
  - irssi
  - mosh
  - screen
  - tmux
  # For SASL in irssi
  - libcrypt-blowfish-perl
  - libcrypt-dh-perl
  - libcrypt-openssl-bignum-perl
  # For jabber in weechat
  - python-xmpp
  # For weechat repo
  - apt-transport-https
- name: Add weechat repository
  apt_repository: repo="deb https://weechat.org/ubuntu trusty main" update_cache=yes
- name: Install weechat-dev
  apt: pkg={{ item }} state=present force=yes # Must use force as the packages are not signed
  with_items:
  - weechat-devel-curses
  - weechat-devel-plugins
- name: Add pubkey help in zprofile
  file: src=zprofile dest=/etc/zsh/zprofile owner=root group=root mode=0644
- name: Add bash Easter egg
  lineinfile: dest=/etc/bash.bashrc state=present line={{ item }}
  with_items:
    - "'function command_not_found_handle { sl -l; }'"
- name: Add zsh Easter egg
  lineinfile: dest=/etc/zsh/zshrc state=present line={{ item }}
  with_items:
    - "'function command_not_found_handler { sl -l; }'"
