---
- name: Configure firewall for account_site
  copy: src=account_site.rules dest=/etc/iptables.d/account_site.rules owner=root group=root mode=0640
  notify:
  - iptables
- name: Copy account files
  copy: src=account dest=/var/www/ owner=root group=root mode=0644 directory_mode=0755
- name: Create config directory
  file: path=/var/www/account/config state=directory owner=root group=www-data mode=0750
- name: Secure config directory
  copy: src=config.htaccess dest=/var/www/account/config/.htaccess owner=root group=root mode=0640
- name: Copy config file
  template: src=config.php dest=/var/www/account/config/config.php owner=root group=www-data mode=0640
- name: Copy config files
  copy: src=secret/account_{{ item }} dest=/var/www/account/config/{{ item }} owner=root group=www-data mode=0640
  with_items:
  - access.list
  - words.txt
- name: Make log file
  file: path=/var/www/account/config/account.log state=touch owner=root group=www-data mode=0660
- name: Add account sites
  copy: src={{ item }}.conf dest=/etc/apache2/sites-available/{{ item }}.conf owner=root group=root mode=0644
  with_items:
  - account
  - accounts
  notify:
  - apache2
- name: Enable account sites
  file: src=../sites-available/{{ item }}.conf dest=/etc/apache2/sites-enabled/{{ item }}.conf state=link owner=root group=root
  with_items:
  - account
  - accounts
  notify:
  - apache2
