---
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
  - ruby-full
  - ruby-dev
  - nodejs
  - build-essential
  - git

- name: Install firewall rules
  copy: src=cvos.rules dest=/etc/iptables.d/cvos.rules owner=root group=root mode=0640
  notify:
  - iptables

- name: Install Jekyll
  gem: name=jekyll state=present user_install=no

- name: Get Site Files
  git: clone=yes depth=1 force=yes dest=/tmp/doc_site repo=https://github.com/collegiumv/cv_doc.git

- name: Create Jekyll site folder
  file: path=/var/www/cvos state=directory owner=root group=root mode=0755

- name: Build CVOS Site
  command: jekyll build --destination=/var/www/cvos/ chdir=/tmp/doc_site

- name: Copy CVOS Site descriptor
  copy: src=cvos.conf dest=/etc/apache2/sites-available/cvos.conf owner=root group=root mode=0644
  notify:
  - apache2

- name: Enable CVOS Site
  file: src=../sites-available/cvos.conf dest=/etc/apache2/sites-enabled/cvos.conf state=link owner=root group=root
  notify:
  - apache2
